# Generated by Django 5.1.1 on 2024-10-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
