# Generated by Django 5.1.1 on 2024-10-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_source_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image_url',
            new_name='urlToImage',
        ),
    ]
