# Generated by Django 5.1.1 on 2024-10-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_published_at_article_publishedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('business', 'Business'), ('sports', 'Sports'), ('health', 'Health')], default='General', max_length=50),
            preserve_default=False,
        ),
    ]
